[general]
live_config_reload = true
import = [
    "~/.alacritty.local.toml",
    "~/.config/alacritty/dracula.toml",
    "~/.config/alacritty/fonts.toml"
]

[font]
size=18

# For legibility checks: 1lI 00
# == === <= >= !! ?? || && ++ -- 
# ‘agrQ£@’

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[window]
option_as_alt = "Both"
dimensions = {columns=120, lines=50}
padding = {x=4, y=0}
