#!/usr/bin/env bash

# Only tested on macOS
# Italics + true color + iTerm + tmux + vim
# https://medium.com/@dubistkomisch/how-to-actually-get-italics-and-true-colour-to-work-in-iterm-tmux-vim-9ebe55ebc2be

cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

tic -x tmux-256color.terminfo
tic -x xterm-256color-italic.terminfo
