export CLICOLOR=1
export LANG="en_US.UTF-8"
export PATH=$PATH:.
export PS1="\h \w \$"

alias ls="ls --color --group-directories-first -F"
alias ll="ls --color --group-directories-first -F -l -t -r"
alias la="ls --color --group-directories-first -F -a"
alias lla="ls --color --group-directories-first -F -la"
alias ,="cd .."
alias m="less"
alias hg="history | grep -i"
alias t="tmux -2 new-session -A -s hello"
alias @="printenv | grep -i"
alias h=history
alias pd='pushd'
alias ,="cd .."

export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=100000
export HISTFILESIZE=100000
shopt -s histappend
shopt -s checkwinsize

if [ -f "/usr/bin/vim" ];
 alias vi="vim"
else
 alias vim="vi"
fi

export EDITOR=nano
