#!/bin/bash

set -eo pipefail

println() { printf '%s\n' "$*"; }
die()     { ret=$?; printf "%s\n" "$@" >&2; exit "$ret"; }

# change directories to the folder hosting this script
readonly _D="$(dirname "$(readlink -f "$0")")" && cd "$_D"

println "• Installing Rust"
curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y

. $HOME/.cargo/env

println "• Installing some great rust CLI utilties"
app=(scrubcsv du-dust xsv hyperfine)
for a in "${app[@]}"
do
    echo "• installing: $a"
    cargo install $a
done

