# Scott Stanfield
# Timing startup
# % hyperfine --warmup 2 'zsh -i -c "exit"'
# Should be < 200 ms

# Profile .zshrc startup times by uncommenting this line:
# zmodload zsh/zprof
# Then start a new zsh. Then run and inspect: zprof > startup.txt

() {
    local d
    for d in \
        "${XDG_CACHE_HOME}/zsh" \
        "${XDG_STATE_HOME}/zsh" \
        "${XDG_DATA_HOME}/zsh" \
        "${XDG_STATE_HOME}/bash" \
        "${XDG_STATE_HOME}/less" \
        "${XDG_STATE_HOME}/python" \
        "${XDG_STATE_HOME}/node" \
        "${XDG_STATE_HOME}/psql" \
        "${XDG_STATE_HOME}/r"; do 
        [[ -d $d ]] || mkdir -p "$d"
    done
}

# this should go in a one-time setup
# mkdir -p -m 755 $XDG_CACHE_HOME $XDG_CONFIG_HOME 
# mkdir -p -m 700 $XDG_DATA_HOME $XDG_STATE_HOME

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
if [[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

in_path() { (( $+commands[$1] )) }

export BLOCK_SIZE="'1"          # Add commas to file sizes
export CLICOLOR=1
export EDITOR=vim
export VISUAL=vim
export LANG="en_US.UTF-8"
export LC_ALL=""
export PAGER=less
UNAME=$(uname)      # Darin, Linux
ARCH=$(arch)        # arm64, i386, x86_64

#########
# HISTORY
#########
HISTFILE="${XDG_STATE_HOME}/zsh/history"
HISTSIZE=50000
SAVEHIST=50000

setopt hist_{'expire_dups_first','find_no_dups','ignore_space','ignore_all_dups','reduce_blanks','verify'}
setopt {'extended','inc_append','share'}_history

setopt NO_caseglob          # case-insensitive globbing
setopt NO_flowcontrol       # disable ctrl-s/ctrl-q flow control in the terminal
setopt NO_nullglob          # unmatched globs pass through as literals (overridden below)
setopt autocd               # cd to a folder just by typing its name
setopt autopushd            # cd pushes old dir onto stack automatically
setopt chaselinks           # resolve symlinks to their true location
setopt extendedglob         # enable extended glob operators: ^, ~, #, etc.
setopt globdots             # WARNING: * matches dotfiles too
setopt globstarshort        # ** as shorthand for **/* 
setopt interactive_comments # allow # comments in shell; good for copy/paste
setopt nullglob             # unmatched globs expand to nothing instead of erroring
setopt numericglobsort      # sort filenames with numbers numerically (file10 > file9)
setopt pushdignoredups      # don't push duplicate dirs onto the stack
setopt pushdsilent          # don't print dir stack after pushd/popd
setopt rcquotes             # allow '' inside single-quoted strings as escaped quote

ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&' # These "eat" the auto prior space after a tab complete

# BINDKEY
bindkey -e
bindkey '\e[3~' delete-char
bindkey '^p'    history-search-backward
bindkey '^n'    history-search-forward
bindkey ' '     magic-space
bindkey $'\e[27;5;13~' accept-line


# Press "ESC" to edit command line in vim
export KEYTIMEOUT=1
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '' edit-command-line

# mass mv: zmv -n '(*).(jpg|jpeg)' 'epcot-$1.$2'
autoload zmv

##
## PATH
##
## These dotfiles assume the GNU core utils are installed. Superior over
## the Mac BSD utilities of the same name. This puts gnu utils first in path.
## Run os/macos.sh to install.
##
## To insert GNU binaries before macOS BSD versions, run this to import matching folders:
## :r! find /opt/homebrew/opt -type d -follow -name gnubin -print
## :r! fd gnubin /opt/homebrew/opt --type d --follow --max-depth 4

#
## It's slow: just add them all, and remove ones that don't match at end
## Same with gnuman
##
## Note: I had /Library/Apple/usr/bin because of /etc/path.d/100-rvictl (REMOVED)
##
## Dangerous to put /usr/local/bin in front of /usr/bin, but yolo 
## https://superuser.com/a/580611
##


# Keep duplicates (Unique) out of these paths
typeset -gU path fpath manpath

if [[ $UNAME == "Darwin" ]]; then
    export HOMEBREW_NO_AUTO_UPDATE=1
    export HOMEBREW_NO_INSTALL_CLEANUP=1
    if [[ $ARCH == "arm64" ]]; then
        export HOMEBREW_PREFIX="/opt/homebrew"
        export HOMEBREW_REPOSITORY="/opt/homebrew"
        export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
        eval "$(/usr/bin/env PATH_HELPER_ROOT="/opt/homebrew" /usr/libexec/path_helper -s)"
        [ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
        export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
    elif [[ $ARCH == "i386" ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi



setopt nullglob

if [[ $UNAME == "Darwin" ]]; then
    local brewpath=$(brew --prefix)
    gnu_bins=(
        /opt/homebrew/bin
        ${brewpath}/opt/coreutils/libexec/gnubin
        ${brewpath}/opt/coreutils/libexec/gnubin
        ${brewpath}/opt/gnu-sed/libexec/gnubin
        ${brewpath}/opt/gawk/libexec/gnubin
        /opt/homebrew/opt/llvm/bin
    )
else
    gnu_bins=()
fi

path=(
    $HOME/.local/share/mise/shims

    $HOME/bin
    $HOME/.local/bin
    ${CARGO_HOME}/bin

    $gnu_bins[@]
    $path[@]

    /usr/bin
    /usr/sbin
    /bin
    /sbin

    ~/dotfile/bin
    .
)

# Now, remove paths that don't exist https://stackoverflow.com/a/9352979
path=($^path(N))

# need mise path early on
[[ -f ~/.local/bin/mise ]] && eval "$(~/.local/bin/mise activate zsh)"

## :r! find /opt/homebrew/opt -type d -follow -name gnuman -print
## :r! fd gnuman /opt/homebrew/opt --type d --follow --max-depth 4
manpath=(

    /opt/homebrew/opt/coreutils/libexec/gnuman/
    /opt/homebrew/opt/gnu-tar/libexec/gnuman/
    /opt/homebrew/opt/gnu-which/libexec/gnuman/
    /opt/homebrew/opt/findutils/libexec/gnuman/
    /opt/homebrew/opt/grep/libexec/gnuman/
    /opt/homebrew/opt/make/libexec/gnuman/
    /opt/homebrew/opt/gawk/libexec/gnuman/
    /opt/homebrew/opt/gsed/libexec/gnuman/
    /opt/homebrew/opt/gnu-sed/libexec/gnuman/

    /usr/local/share/man
    /usr/share/man

    $manpath[@]
)
manpath=($^manpath(N))
setopt NO_nullglob

export MANROFFOPT="-c"
if in_path bat; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

if in_path batcat; then
    alias bat='batcat'
    export MANPAGER="sh -c 'col -bx | batat -l man -p'"
fi

## LS and colors
## Tips: https://gist.github.com/syui/11322769c45f42fad962

# ensure basic /bin/ls has colors and aliases

export CLICOLOR=1
alias ls="ls -GF "
alias la="ls -GF -a"
alias ll="ls -GF -l --sort=extension"
alias lla="ls -GF -la"

# GNU and BSD (macOS) ls flags aren't compatible
# On macOS, installing GNU ls lands as "gls"
# But on Linux, it's just "ls" and it responds to --version,
# whereas BSD does not.

if in_path gls; then
    lspath=$(whence -p "gls")
fi
if [[ $(ls --version &>/dev/null) ]]; then
    lspath=$(whence -p ls)
fi

## GNU ls settings
if in_path gls || ls --version &>/dev/null; then
    lsflags="--color --group-directories-first -F "
    alias ls="ls ${lsflags} "
    alias la="ls ${lsflags} -a"
    alias ll="ls ${lsflags} -l --sort=extension"
    alias lla="ls ${lsflags} -la"
    alias lln="ls ${lsflags} -l"

    lsflags+=" --no-user --no-permissions"
    alias l="ll"
    alias lld="ls ${lsflags} -l --sort=time --time-style=full-iso"
    alias llD="ls ${lsflags} -l --sort=time --reverse --time-style=full-iso"
    alias lls="ls ${lsflags} -l --sort=size "
    alias llS="ls ${lsflags} -l --sort=size --reverse"
    alias lle="ls ${lsflags} -l --sort=extension "
fi

## eza/exa settings for ls
if in_path eza; then
    ignorefiles=' --ignore-glob "Library|Music|Movies|Pictures|Public|Applications|Creative Cloud Files" '
    ezaflags="--classify --color-scale --bytes --group-directories-first"
    ezaflags+=${ignorefiles}

    function els() { eza --classify --color-scale --bytes --group-directories-first $@ }
    alias ls="eza ${ezaflags} "$*" "
    alias ll="eza ${ezaflags} -l "$*" "
    alias ell="eza ${ezaflags} --long --git"
    alias eld="eza ${ezaflags} --all --long --sort date"
    alias elt="eza ${ezaflags} --all --long --sort date"
    alias ele="eza ${ezaflags} --all --long --sort extension"
    alias elss="eza ${ezaflags} --all --long --sort size"

    export EZA_CONFIG_DIR=${XDG_CONFIG_HOME}/eza

    export EZA_COLORS="\
    di=3:\
    da=34:\
    gr=34:\
    gu=37:\
    gw=35:\
    gx=36:\
    sb=32:\
    sn=32:\
    tr=34:\
    tw=35:\
    tx=36:\
    ue=36:\
    ur=34:\
    uu=36:\
    uw=35:\
    ux=36:\
    "

    if [[ -d "$HOME/.config/eza" ]]; then
        export EZA_CONFIG_DIR=$HOME/.config/eza
    fi
fi


# envgrep or @
# Quick search for environment varibles. Usage:
# @ xdg ==> shows all the XDG variables
function @() {
    local exclude='^(PATH|.*COLOR.*)='
    if [ "$#" -eq 0 ]; then
        printenv | sort | grep -vE "$exclude" | less
    else
        printenv | sort | grep -vE "$exclude" | grep --ignore-case --color=always "$1"
    fi
}

## ALIASES go here
alias ,="cd .."
alias cx="chmod +x"
alias gd="git diff"
alias b="bat"
alias cp="cp -a"
alias d='dirs -v'
alias dc='docker compose'
alias ddb="duckdb"
alias df='df --human-readable'
alias dkrr='docker run --rm -it -u1000:1000 -v$(pwd):/work -w /work -e DISPLAY=$DISPLAY'
alias dust='dust -r'
alias ga="git add"
alias grep="grep --color=auto"
alias gs="git status 2>/dev/null"
alias ga="git add"
alias h="history 0"
alias ha="history 9999"
alias hg="history 1 | grep -i"
alias ips="ip -4 --color --brief a"
alias logs="docker logs control -f"
alias m="less"
alias p="python3"
alias path='echo $PATH | tr : "\n" | cat -n'
alias pd='pushd'  # symmetry with cd
alias r="R --no-save --no-restore-data --quiet"
alias R="R --no-save --no-restore-data "
alias rg="rg --pretty --smart-case --no-require-git -g '!*.lock' "
alias rsp="rsync -avlhW --info=progress2,stats "
alias sc='systemctl'
alias scp='scp -p'
alias ssh="TERM=xterm-256color ssh"
alias sudosu="sudo -Es"
alias t='tmux -2 new-session -A -s "moab"'
alias td='tmux detach'
alias ts='tmux source ~/.tmux.conf'
alias uv="uv --native-tls"
alias uvx="uvx --native-tls"
alias cleanbash='env -i HOME=$HOME TERM=$TERM PATH=/usr/bin:/bin:/usr/sbin:/sbin bash '

function anybar { echo -n $1 | nc -4u -w0 localhost ${2:-1738}; }

function mx() {
  local tool="$1"
  shift || true
  mise exec "${tool}@latest" -- "$tool" "$@"
}


# function fif() {
#   if [ ! "$#" -gt 0 ]; then echo "Need a string to search for!"; return 1; fi
#   rg --color=never --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
# }

function jl()      { < $1 jq -C . | less $LESS }
function gg()      { git commit -m "$*" }
function httpie    { command http --pretty=all --verbose $@ | less -R; }
function ht()      { (head $1 && echo "---" && tail $1) | less }
function take()    { mkdir -p $1 && cd $1 }
function cols()    { head -1 $1 | tr , \\n | cat -n | column }		# show CSV header
function zcolors() { for code in {000..255}; do print -P -- "$code: %F{$code}Test%f"; done | column}
function git3()    { git fetch upstream && git merge upstream/main && git push }

# Automatically ls after you cd
function chpwd() {
    emulate -L zsh
    ls -F
}

less_options=(
    --quit-if-one-screen     # -F If the entire text fits on one screen, just show it and quit. (like cat)
    --no-init                # -X Do not clear the screen first.
    --ignore-case            # -i Like "smartcase" in Vim: ignore case unless the search pattern is mixed.
    --chop-long-lines        # -S Do not automatically wrap long lines.
    --RAW-CONTROL-CHARS      # -R Allow ANSI colour escapes, but no other escapes.
    --LONG-PROMPT            # -M most verbose prompt
);
export LESS="${less_options[*]}";

## vi / vim / neovim (nvim)

# vi alias points to nvim or vim
which "nvim" &> /dev/null && _vi="nvim" || _vi="vim"
export EDITOR=${_vi}
alias vi="${_vi} -o"
alias v=vi

# zshrc and vimrc aliases to edit these two files
alias zshrc="${_vi} ~/.zshrc"
if [[ $EDITOR  == "nvim" ]]; then
    alias vimrc="nvim ~/.config/nvim/init.vim"
else
    alias vimrc="vim ~/.vimrc"
fi

# Put your machine-specific settings here
[[ -f $HOME/.zshrc.local ]] && source $HOME/.zshrc.local

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#   Zsh interactive setup (old zinit zdharma stuff)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PLUGIN_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins

# Source a file if it exists; warn and continue if it doesn't.
# Accepts a path relative to $PLUGIN_DIR or an absolute path.
safe_source() {
    local f=$1
    [[ $f = /* ]] || f=$PLUGIN_DIR/$f
    if [[ -f $f ]]; then
        source $f
    else
        print -u2 "warning: $f not found, skipping"
    fi
}

# 1. Completion system: fpath, zstyles, compinit, options.
setup_completion() {
    fpath=(
        /opt/homebrew/share/zsh/site-functions
        ${HOME}/.local/share/zsh/completions
        $fpath
    )
    typeset -gU fpath

    zstyle ':completion:*' menu select
    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
    zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
    zstyle ':completion:*' completer _expand _complete _match _approximate
    zstyle ':completion:*' list-suffixes
    zstyle ':completion:*' expand prefix suffix

    autoload -Uz compinit
    local zcd=${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump
    mkdir -p ${zcd:h}
    # Full security check once a day; otherwise trust the cache.
    if [[ -n $zcd(#qN.mh+24) ]]; then
        compinit -d $zcd
    else
        compinit -C -d $zcd
    fi
    [[ -f $zcd && ( ! -f $zcd.zwc || $zcd -nt $zcd.zwc ) ]] && \
        zcompile -R -- $zcd.zwc $zcd

    setopt complete_in_word   # cd /ho/sco/tm<TAB> expands inline
    setopt auto_menu          # show completion menu on successive tab presses
}

# 2. Plugins: prompt theme, autosuggestions, syntax highlighting, p10k config.
setup_plugins() {
    safe_source powerlevel10k/powerlevel10k.zsh-theme              # prompt theme
    safe_source fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh  # syntax coloring (load last)
    [[ -f ${XDG_CONFIG_HOME}/zsh/p10k.zsh ]] && source ${XDG_CONFIG_HOME}/zsh/p10k.zsh
}

# 3. fast-syntax-highlighting theme + style tweaks (runs after setup_plugins).
setup_fsh_theme() {
    local marker=${XDG_DATA_HOME:-$HOME/.local/share}/zsh/fast-syntax-highlighting-configured
    if (( $+functions[fast-theme] )) && [[ ! -f $marker ]]; then
        fast-theme -q default
        touch $marker
    fi
    if (( ${+FAST_HIGHLIGHT_STYLES} )); then
        FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}path]='fg=cyan'
        FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}path-to-dir]='fg=cyan,underline'
        FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}comment]='fg=gray'
    fi
}

# 4. ssh-agent: reuse running agent or start a new one.
setup_ssh_agent() {
    # If we can already reach an agent (with or without keys), reuse it.
    ssh-add -l &>/dev/null
    [[ $? -ne 2 ]] && return   # exit 0 = has keys, 1 = empty but alive; both fine

    # Try the saved env from a previous session.
    [[ -f $HOME/.ssh-agent-env ]] && source $HOME/.ssh-agent-env >/dev/null
    ssh-add -l &>/dev/null
    [[ $? -ne 2 ]] && return   # the saved agent is alive — reuse it

    # No reachable agent anywhere; start a fresh one.
    ssh-agent > $HOME/.ssh-agent-env
    chmod 600 $HOME/.ssh-agent-env
    source $HOME/.ssh-agent-env >/dev/null
}

# Run them in order.
setup_plugins
setup_fsh_theme
setup_ssh_agent
setup_completion

################
## END OF ZINIT
################

unsetopt correct
unsetopt correct_all
setopt complete_in_word         # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt auto_menu                # show completion menu on succesive tab presses


################
## END OF ZINIT
################

export prompticons=( 󰯉 󰊠         ▼         󰆚 󰀘 󱍢 󰦥)

# Having this instant_* function prevents the "flash of unstyled content"
function instant_prompt_my_host_icon() {
    prompt_my_host_icon
}
function prompt_my_host_icon() {
    # if prompt_icon_index is set, use that
    # if host_icon is set, use that instead

    pi1=$prompticons[${PROMPT_ICON_INDEX:-3}]
    pi1=${HOST_ICON:-$pi1}
    p10k segment -i $pi1 -f ${HOST_ICON_COLOR:-4}

    unset p
}

export BAT_THEME="gruvbox-dark"

# R language settings
export R_LIBS="~/.R/libs"
export R_OPENMP_ENABLED=1
export PKG_CFLAGS="${PKG_CFLAGS} -fopenmp"
export PKG_LIBS="${PKG_LIBS} -fopenmp"

export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
export CFLAGS="-I/opt/homebrew/opt/llvm/include"

(( $+commands[fzf] )) && source <(fzf --zsh)
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='»'
