[tools]
delta        = "latest"
difftastic   = "latest"
duf          = "latest"          # disk usage
eza          = "latest"
fzf          = "latest"
glow         = "latest"
jq           = "latest"
lazygit      = "latest"
neovim       = "latest"
rg           = "latest"           # ripgrep
uv           = "latest"
yq           = "latest"

# lnav = "latest"       # log navigator

[settings.pipx]
uvx = true
